CREATE DATABASE IF NOT EXISTS TripLogger;
USE TripLogger;
CREATE TABLE IF NOT EXISTS Vehicles(
id int NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(100),
vehicle VARCHAR(100)
);
CREATE TABLE IF NOT EXISTS Trips(
id int NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(60) NOT NULL,
address VARCHAR(80) NOT NULL,
lat FLOAT(10,6) NOT NULL,
lon FLOAT(10,6) NOT NULL,
type VARCHAR(30) NOT NULL,
vehicle_id int REFERENCES Vehicles
);
