CREATE DATABASE IF NOT EXISTS TripLogger;
USE TripLogger;
CREATE TABLE IF NOT EXISTS Vehicles(
id int NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(100),
vehicle VARCHAR(100)
);
CREATE TABLE IF NOT EXISTS Trips(
id int NOT NULL AUTO_INCREMENT PRIMARY KEY,
vehicle_id int REFERENCES Vehicles,
location VARCHAR(100),
lat FLOAT(10,6),
lon FLOAT(10,6)
);
